using UnityEngine;
// NOTE: STEAM IDENTITY PROVIDER IS LOCKED BEHIND A PAYWALL, USE MANUAL EMAIL / PASSWORD LOGIN FOR NOW, IMPLEMENT THE AUTOMATIC STEAM AUTH LATER

public class LoginManager : MonoBehaviour {
    
}